### ISSUE TITLE
请问可以加入影片名和日期等选项吗？

### ISSUE THREAD

**Issue by lfeng35** [CheerChen/dmm-scraper#29]
作者您好，

请问可以出了现有的{year} {maker} {num} {actor}之外，可以添加影片标题和具体发行日期等选项吗？这样方便按日期整理

谢谢

**Comment by CheerChen** [comment]
想确认一下，你是希望目录名里面有影片标题和具体发行日期吗，发行日期也许可行，标题可能会因为特殊字符导致目录创建失败……
